### PR TITLE
Fix typo on README.md

### PR DESCRIPTION
**Pull request by ifeanyi2667**
There was an error on the README markdown file, which I corrected.
'close' was used instead of 'onClose' in the doc.

### CODE REVIEW

**Comment by ashinzekene** [comment]
Thanks for this!

**Comment by ashinzekene** [comment]
Can you help in making changes to `src/app/app.component.ts` too?

**Comment by ifeanyi2667** [comment]
Ok Done

**Comment by ashinzekene** [comment]
Fixes #32

**Comment by ashinzekene** [comment]
Thanks!

**Pull request merged**
