### PR TITLE
changed (close) events to (onClose).

### PR DESCRIPTION
**Pull request by hellotunmbi**
The close event name is 'onClose' but the code documentation says 'close'. (close) obviously didn't work but (onClose) did.

I fixed this typo in the README.md and included examples.

### CODE REVIEW

**Comment by ashinzekene** [comment]
Thanks a lot for this. Sorry I was unable to review since

Please can you help check that the changes are only for the `onClose` you worked on?

**Comment by hellotunmbi** [comment]
Yes, I only worked on the `onClose` event and updated it in the Readme file

**Comment by ashinzekene** [comment]
Hello @hellotunmbi checking the [diff](https://github.com/ashinzekene/angular4-paystack/pull/27/files) it shows there are a lot of other changes other than the one intended. Please make a correction to this

**Comment by ashinzekene** [comment]
Sorry had to close this

**Pull request closed without merging**
