### PR TITLE
Split Code Option Added

### PR DESCRIPTION
**Pull request by onyilo**
Split Code Option Added. This is to allow automatic multiple split payments

### CODE REVIEW

**Comment by DevDianDankie** [comment]
Hi, I also came across the need for this. What is still required to get it in?

**Comment by ashinzekene** [comment]
Hi @DevDianDankie, some unnecessary file changes need to be reverted

**Comment by DevDianDankie** [comment]
Hi @ashinzekene for now I pulled in the module directly into my project and updated it there.

But just thought to point it out.

**Review by ashinzekene — APPROVED** [review]

**Comment by ashinzekene** [comment]
Thanks for the help @DevDianDankie and sorry for the late response, could you please fix the merge conflicts and let's get this in?

**Review by onyilo — COMMENTED** [review]
Change Reviewed

**Review by ashinzekene — APPROVED** [review]

**Review by ashinzekene — CHANGES_REQUESTED** [review]
I think there are still conflicts in the PR

**Comment by ashinzekene** [comment]
#85

Fixed in this PR @onyilo @DevDianDankie

**Comment by ashinzekene** [comment]
Fixed in another PR

**Pull request closed without merging**
